# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caab5ad8d9d566a508846dc886bc147301d1928ca71a54f24237676bbbf73dfaf6095e9802e57e88ff695adf6d1750c9eed51cb8fef104c04c78ba5e964e8863

test:
  secret_key_base: cf05ea891f6f213d017f18995128cff9549bd4d873cac4f9cd587734137f8a719c5ba0e63ed08d6d94148140a98e4750dce4b868234dec2d7997226ea72c9e76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
